path: /var/www/web
config create:
  dbhost: mysql
  dbuser: root
  dbpass: password
  extra-php: |
    define( 'DISALLOW_FILE_EDIT', true );
    define( 'WP_DEBUG', true );
    define( 'SAVEQUERIES', true );
